
    console.log('%cЗадание №2', 'padding: 20px 0; font-weight: bold; font-size: 18px')
    let a1 = 5/3
    let a2 = 3/5
    let a3 = 5+'3'
    let a4 = '5'-3
    let a5 = 75+'кг'
    let a6 = 785*653
    let a7 = 100/25
    let a8 = 0*0
    let a9 = 0/2
    let a10 = 89/0
    let a11 = 98+2
    let a12 = 5-98
    let a13 = (8+56*4)/5
    let a14 = (9-12)*7/(5+2)
    let a15 = +'123'
    let a16 = 1 || 0
    let a17 = false || true
    let a18 = true > 0
    console.log('Переменная a1=', a1, 'тип данных - ', typeof a1)
    console.log('Переменная a2=', a2, 'тип данных - ', typeof a2)
    console.log('Переменная a3=', a3, 'тип данных - ', typeof a3)
    console.log('Переменная a4=', a4, 'тип данных - ', typeof a4)
    console.log('Переменная a5=', a5, 'тип данных - ', typeof a5)
    console.log('Переменная a6=', a6, 'тип данных - ', typeof a6)
    console.log('Переменная a7=', a7, 'тип данных - ', typeof a7)
    console.log('Переменная a8=', a8, 'тип данных - ', typeof a8)
    console.log('Переменная a9=', a9, 'тип данных - ', typeof a9)
    console.log('Переменная a10=', a10, 'тип данных - ', typeof a10)
    console.log('Переменная a11=', a11, 'тип данных - ', typeof a11)
    console.log('Переменная a12=', a12, 'тип данных - ', typeof a12)
    console.log('Переменная a13=', a13, 'тип данных - ', typeof a13)
    console.log('Переменная a14=', a14, 'тип данных - ', typeof a14)
    console.log('Переменная a15=', a15, 'тип данных - ', typeof a15)
    console.log('Переменная a16=', a16, 'тип данных - ', typeof a16)
    console.log('Переменная a17=', a17, 'тип данных - ', typeof a17)
    console.log('Переменная a18=', a18, 'тип данных - ', typeof a18)   